version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: loan_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loan_predictions
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: loan_fastapi_backend
    restart: always
    ports:
      - "8080:7860"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/loan_predictions
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: loan_streamlit_frontend
    restart: always
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:7860
    depends_on:
      - backend

volumes:
  mysql_data:
